title: "Scala 2014 | 5th Annual Scala Workshop, Co-Located with ECOOP | July 28-29th, 2014. Uppsala, Sweden"
baseurl: ""

# destination: ../../public_html/scala2013
# baseurl: http://lampwww.epfl.ch/~hmiller/scala2013
