title: "Scala 2013 | 4th Annual Scala Workshop, Co-Located with ECOOP | July 2nd, 2013. Montpellier, France"
baseurl: ""

# destination: ../../public_html/scala2013
# baseurl: http://lampwww.epfl.ch/~hmiller/scala2013
